# Use SVM to attempt to classify currency pairs based on historic OfferCreate data

In [13]:
import pandas as pd
from sklearn.preprocessing import MinMaxScaler

In [8]:
df = pd.read_csv('Ledger_Account_Currency_Pairs_2024-12-04.csv')

In [9]:
df.head()

,Ledger_Number,Ledger_Date,Account_ID,Gets_Currency_Code,Pays_Currency_Code,Row_Count,Transaction_Fee_med,Transaction_Fee_avg,Transaction_Fee_max,Transaction_Fee_min,...,Gets_Count_med,Gets_Count_avg,Gets_Count_max,Gets_Count_min,Gets_Count_sum,Pays_Count_med,Pays_Count_avg,Pays_Count_max,Pays_Count_min,Pays_Count_sum
0,67399995,2021-10-31T20:44:10.000Z,r4AZpDKVoBxVcYUJCWMcqZzyWsHTteC4ZE,XRP,CNY,8,12.0,12.0,12.0,12.0,...,5.398351e+09,6.343232e+09,1.117005e+10,2.089043e+09,5.074585e+10,4.250282e+04,4.866140e+04,8.657482e+04,1.466222e+04,3.892912e+05
1,67399995,2021-10-31T20:44:10.000Z,r4dgY6Mzob3NVq8CFYdEiPnXKboRScsXRu,CNY,XRP,5,12.0,12.0,12.0,12.0,...,2.705472e+04,4.674482e+04,1.195828e+05,1.197346e+04,2.337241e+05,4.016121e+09,7.136296e+09,1.775767e+10,2.064215e+09,3.568148e+10
2,67399995,2021-10-31T20:44:10.000Z,rDogkw75XgwYfAcX4om7jYUgZyXvQrkh6i,5852646F67650000000000000000000000000000,XRP,1,20.0,20.0,20.0,20.0,...,3.902439e+05,3.902439e+05,3.902439e+05,3.902439e+05,3.902439e+05,1.200000e+08,1.200000e+08,1.200000e+08,1.200000e+08,1.200000e+08
3,67399995,2021-10-31T20:44:10.000Z,rDogkw75XgwYfAcX4om7jYUgZyXvQrkh6i,XRP,5852646F67650000000000000000000000000000,1,20.0,20.0,20.0,20.0,...,1.200000e+08,1.200000e+08,1.200000e+08,1.200000e+08,1.200000e+08,4.041765e+05,4.041765e+05,4.041765e+05,4.041765e+05,4.041765e+05
4,67399995,2021-10-31T20:44:10.000Z,rFSEzZAJUooos1DzxzDiFGaY7SUZkyrZc,FSE,XRP,1,20.0,20.0,20.0,20.0,...,4.431438e+00,4.431438e+00,4.431438e+00,4.431438e+00,4.431438e+00,7.000000e+07,7.000000e+07,7.000000e+07,7.000000e+07,7.000000e+07

### Eliminate Ledger_Number, atp just a muddy Ledger_Date substitute

In [12]:
df = df.drop(columns=['Ledger_Number'])

### Must scale Numeric Data

In [ ]:
scaler = MinMaxScaler()